// <auto-generated />
using System;
using Arendehanteringssystem.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arendehanteringssystem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230318214207_DatabaseIsBorn")]
    partial class DatabaseIsBorn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arendehanteringssystem.Models.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("char(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Arendehanteringssystem.Models.Entities.ErrandEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("ErrandDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Errand");
                });

            modelBuilder.Entity("Arendehanteringssystem.Models.Entities.StatusAndCommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ErrandId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ErrandId")
                        .IsUnique();

                    b.ToTable("StatusAndComment");
                });

            modelBuilder.Entity("Arendehanteringssystem.Models.Entities.ErrandEntity", b =>
                {
                    b.HasOne("Arendehanteringssystem.Models.Entities.CustomerEntity", "Customer")
                        .WithMany("Errands")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Arendehanteringssystem.Models.Entities.StatusAndCommentEntity", b =>
                {
                    b.HasOne("Arendehanteringssystem.Models.Entities.ErrandEntity", "Errand")
                        .WithOne("StatusAndComment")
                        .HasForeignKey("Arendehanteringssystem.Models.Entities.StatusAndCommentEntity", "ErrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Errand");
                });

            modelBuilder.Entity("Arendehanteringssystem.Models.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Errands");
                });

            modelBuilder.Entity("Arendehanteringssystem.Models.Entities.ErrandEntity", b =>
                {
                    b.Navigation("StatusAndComment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
